spring:
  application:
    name: OnlineOrderSystemApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/OnlineOrder?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    name: user