spring:
  application:
    name: OnlineOrderSystemApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/OnlineOrder?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    name: user
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.onlineorder.onlineordersystem.model.dao
logging:
  level:
    root: info
    org.springframework.jdbc: debug  # 显示事务控制日志
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%logger{50}){cyan} %clr(:){faint} %msg%n"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl